### ISSUE TITLE
ndpi_main.h

### ISSUE THREAD

**Issue by bdpreom** [dreadl0ck/netcap#23]
hi ,

for go 1.17.1 wrapper for ndpi is generating follwing issue

`nDPI_wrapper.go:6:
./nDPI_wrapper_impl.h:3:10: fatal error: 'ndpi/ndpi_main.h' file not found
#include <ndpi/ndpi_main.h>
         ^~~~~~~~~~~~~~~~~~`

**Comment by dreadl0ck** [comment]
Hi,

this has nothing to do with your Go version - it happens because the deep packet inspection C library _libndpi_ is not installed on your system, you will need libprotoident as well.

You can compile the project without bindings to ndpi and libprotoident, by passing the 'nodpi' flag to the go compiler.

Eg:

````
go build -tags nodpi -ldflags "-s -w" -o bin/net github.com/dreadl0ck/netcap/cmd
```


Or just use a nodpi build from the compiled releases.
